const hiraganaCharacters = [
  { question: "あ", options: ["A", "I", "U", "E"], answer: "A" },
  { question: "い", options: ["I", "E", "O", "U"], answer: "I" },
  { question: "う", options: ["U", "E", "I", "O"], answer: "U" },
  { question: "え", options: ["E", "O", "A", "I"], answer: "E" },
  { question: "お", options: ["O", "U", "I", "A"], answer: "O" },
  { question: "か", options: ["KA", "KI", "KU", "KE"], answer: "KA" },
  { question: "き", options: ["KI", "KE", "KO", "KU"], answer: "KI" },
  { question: "く", options: ["KU", "KO", "KE", "KI"], answer: "KU" },
  { question: "け", options: ["KE", "KU", "KI", "KO"], answer: "KE" },
  { question: "こ", options: ["KO", "KE", "KI", "KU"], answer: "KO" },
  { question: "さ", options: ["SA", "SHI", "SU", "SE"], answer: "SA" },
  { question: "し", options: ["SHI", "SU", "SE", "SA"], answer: "SHI" },
  { question: "す", options: ["SU", "SE", "SA", "SHI"], answer: "SU" },
  { question: "せ", options: ["SE", "SA", "SHI", "SU"], answer: "SE" },
  { question: "そ", options: ["SO", "SE", "SU", "SA"], answer: "SO" },
  { question: "た", options: ["TA", "CHI", "TSU", "TE"], answer: "TA" },
  { question: "ち", options: ["CHI", "TSU", "TE", "TA"], answer: "CHI" },
  { question: "つ", options: ["TSU", "TE", "TA", "CHI"], answer: "TSU" },
  { question: "て", options: ["TE", "TA", "CHI", "TSU"], answer: "TE" },
  { question: "と", options: ["TO", "TE", "TSU", "TA"], answer: "TO" },
  { question: "な", options: ["NA", "NI", "NU", "NE"], answer: "NA" },
  { question: "に", options: ["NI", "NU", "NE", "NA"], answer: "NI" },
  { question: "ぬ", options: ["NU", "NE", "NA", "NI"], answer: "NU" },
  { question: "ね", options: ["NE", "NA", "NI", "NU"], answer: "NE" },
  { question: "の", options: ["NO", "NE", "NU", "NA"], answer: "NO" },
  { question: "は", options: ["HA", "HI", "FU", "HE"], answer: "HA" },
  { question: "ひ", options: ["HI", "FU", "HE", "HA"], answer: "HI" },
  { question: "ふ", options: ["FU", "HE", "HA", "HI"], answer: "FU" },
  { question: "へ", options: ["HE", "HA", "HI", "FU"], answer: "HE" },
  { question: "ほ", options: ["HO", "HE", "FU", "HA"], answer: "HO" },
  { question: "ま", options: ["MA", "MI", "MU", "ME"], answer: "MA" },
  { question: "み", options: ["MI", "MU", "ME", "MA"], answer: "MI" },
  { question: "む", options: ["MU", "ME", "MA", "MI"], answer: "MU" },
  { question: "め", options: ["ME", "MA", "MI", "MU"], answer: "ME" },
  { question: "も", options: ["MO", "ME", "MU", "MA"], answer: "MO" },
  { question: "や", options: ["YA", "YU", "YO", "E"], answer: "YA" },
  { question: "ゆ", options: ["YU", "YO", "E", "YA"], answer: "YU" },
  { question: "よ", options: ["YO", "E", "YA", "YU"], answer: "YO" },
  { question: "ら", options: ["RA", "RI", "RU", "RE"], answer: "RA" },
  { question: "り", options: ["RI", "RU", "RE", "RA"], answer: "RI" },
  { question: "る", options: ["RU", "RE", "RA", "RI"], answer: "RU" },
  { question: "れ", options: ["RE", "RA", "RI", "RU"], answer: "RE" },
  { question: "ろ", options: ["RO", "RE", "RU", "RA"], answer: "RO" },
  { question: "わ", options: ["WA", "WO", "N", "RA"], answer: "WA" },
  { question: "を", options: ["WO", "N", "O", "WA"], answer: "WO" },
  { question: "ん", options: ["N", "M", "V", "B"], answer: "N" },
  // Dakuten Characters
  { question: "が", options: ["GA", "GI", "GU", "GE"], answer: "GA" },
  { question: "ぎ", options: ["GI", "GU", "GE", "GA"], answer: "GI" },
  { question: "ぐ", options: ["GU", "GE", "GA", "GI"], answer: "GU" },
  { question: "げ", options: ["GE", "GA", "GI", "GU"], answer: "GE" },
  { question: "ご", options: ["GO", "GE", "GU", "GA"], answer: "GO" },
  { question: "ざ", options: ["ZA", "JI", "ZU", "ZE"], answer: "ZA" },
  { question: "じ", options: ["JI", "ZU", "ZE", "ZA"], answer: "JI" },
  { question: "ず", options: ["ZU", "ZE", "ZA", "JI"], answer: "ZU" },
  { question: "ぜ", options: ["ZE", "ZA", "JI", "ZU"], answer: "ZE" },
  { question: "ぞ", options: ["ZO", "ZE", "ZU", "ZA"], answer: "ZO" },
  { question: "だ", options: ["DA", "JI", "DU", "DE"], answer: "DA" },
  { question: "ぢ", options: ["JI", "DU", "DE", "DA"], answer: "JI" },
  { question: "づ", options: ["DU", "DE", "DA", "JI"], answer: "DU" },
  { question: "で", options: ["DE", "DA", "JI", "DU"], answer: "DE" },
  { question: "ど", options: ["DO", "DE", "DA", "DU"], answer: "DO" },
  // Han-Dakuten Characters
  { question: "ぱ", options: ["PA", "PI", "PU", "PE"], answer: "PA" },
  { question: "ぴ", options: ["PI", "PU", "PE", "PA"], answer: "PI" },
  { question: "ぷ", options: ["PU", "PE", "PA", "PI"], answer: "PU" },
  { question: "ぺ", options: ["PE", "PA", "PI", "PU"], answer: "PE" },
  { question: "ぽ", options: ["PO", "PE", "PA", "PI"], answer: "PO" },
  // Dakuten Combinations
  { question: "ぎゃ", options: ["GYA", "GYU", "GYO", "GE"], answer: "GYA" },
  { question: "ぎゅ", options: ["GYU", "GYO", "GE", "GYA"], answer: "GYU" },
  { question: "ぎょ", options: ["GYO", "GE", "GYA", "GYU"], answer: "GYO" },
  { question: "じゃ", options: ["JA", "JU", "JO", "JE"], answer: "JA" },
  { question: "じゅ", options: ["JU", "JO", "JE", "JA"], answer: "JU" },
  { question: "じょ", options: ["JO", "JE", "JA", "JU"], answer: "JO" },
  { question: "びゃ", options: ["BYA", "BYU", "BYO", "BE"], answer: "BYA" },
  { question: "びゅ", options: ["BYU", "BYO", "BE", "BYA"], answer: "BYU" },
  { question: "びょ", options: ["BYO", "BE", "BYA", "BYU"], answer: "BYO" },
  { question: "ぴゃ", options: ["PYA", "PYU", "PYO", "PE"], answer: "PYA" },
  { question: "ぴゅ", options: ["PYU", "PYO", "PE", "PYA"], answer: "PYU" },
  { question: "ぴょ", options: ["PYO", "PE", "PYA", "PYU"], answer: "PYO" },
  // Han-Dakuten Combinations
  { question: "きゃ", options: ["KYA", "KYU", "KYO", "KE"], answer: "KYA" },
  { question: "きゅ", options: ["KYU", "KYO", "KE", "KYA"], answer: "KYU" },
  { question: "きょ", options: ["KYO", "KE", "KYA", "KYU"], answer: "KYO" },
  { question: "しゃ", options: ["SHA", "SHU", "SHO", "SE"], answer: "SHA" },
  { question: "しゅ", options: ["SHU", "SHO", "SE", "SHA"], answer: "SHU" },
  { question: "しょ", options: ["SHO", "SE", "SHA", "SHU"], answer: "SHO" },
  { question: "ちゃ", options: ["CHA", "CHU", "CHO", "CHE"], answer: "CHA" },
  { question: "ちゅ", options: ["CHU", "CHO", "CHE", "CHA"], answer: "CHU" },
  { question: "ちょ", options: ["CHO", "CHE", "CHA", "CHU"], answer: "CHO" },
  { question: "にゃ", options: ["NYA", "NYU", "NYO", "NE"], answer: "NYA" },
  { question: "にゅ", options: ["NYU", "NYO", "NE", "NYA"], answer: "NYU" },
  { question: "にょ", options: ["NYO", "NE", "NYA", "NYU"], answer: "NYO" }
];

const katakanaCharacters = [
  { question: "ア", options: ["A", "I", "U", "E"], answer: "A" },
  { question: "イ", options: ["I", "E", "O", "U"], answer: "I" },
  { question: "ウ", options: ["U", "E", "I", "O"], answer: "U" },
  { question: "エ", options: ["E", "O", "A", "I"], answer: "E" },
  { question: "オ", options: ["O", "U", "I", "A"], answer: "O" },
  { question: "カ", options: ["KA", "KI", "KU", "KE"], answer: "KA" },
  { question: "キ", options: ["KI", "KE", "KO", "KU"], answer: "KI" },
  { question: "ク", options: ["KU", "KO", "KE", "KI"], answer: "KU" },
  { question: "ケ", options: ["KE", "KU", "KI", "KO"], answer: "KE" },
  { question: "コ", options: ["KO", "KE", "KI", "KU"], answer: "KO" },
  { question: "サ", options: ["SA", "SHI", "SU", "SE"], answer: "SA" },
  { question: "シ", options: ["SHI", "TSU", "SE", "SA"], answer: "SHI" },
  { question: "ス", options: ["SU", "SE", "SA", "SHI"], answer: "SU" },
  { question: "セ", options: ["SE", "SA", "SHI", "SU"], answer: "SE" },
  { question: "ソ", options: ["SO", "N", "SU", "SA"], answer: "SO" },
  { question: "タ", options: ["TA", "CHI", "TSU", "TE"], answer: "TA" },
  { question: "チ", options: ["CHI", "TSU", "TE", "TA"], answer: "CHI" },
  { question: "ツ", options: ["TSU", "TE", "TA", "SHI"], answer: "TSU" },
  { question: "テ", options: ["TE", "TA", "CHI", "TSU"], answer: "TE" },
  { question: "ト", options: ["TO", "TE", "TSU", "TA"], answer: "TO" },
  { question: "ナ", options: ["NA", "NI", "NU", "NE"], answer: "NA" },
  { question: "ニ", options: ["NI", "NU", "NE", "NA"], answer: "NI" },
  { question: "ヌ", options: ["NU", "NE", "NA", "NI"], answer: "NU" },
  { question: "ネ", options: ["NE", "NA", "NI", "NU"], answer: "NE" },
  { question: "ノ", options: ["NO", "NE", "NU", "NA"], answer: "NO" },
  { question: "ハ", options: ["HA", "HI", "FU", "HE"], answer: "HA" },
  { question: "ヒ", options: ["HI", "FU", "HE", "HA"], answer: "HI" },
  { question: "フ", options: ["FU", "HE", "HA", "HI"], answer: "FU" },
  { question: "ヘ", options: ["HE", "HA", "HI", "FU"], answer: "HE" },
  { question: "ホ", options: ["HO", "HE", "FU", "HA"], answer: "HO" },
  { question: "マ", options: ["MA", "MI", "MU", "ME"], answer: "MA" },
  { question: "ミ", options: ["MI", "MU", "ME", "MA"], answer: "MI" },
  { question: "ム", options: ["MU", "ME", "MA", "MI"], answer: "MU" },
  { question: "メ", options: ["ME", "MA", "MI", "MU"], answer: "ME" },
  { question: "モ", options: ["MO", "ME", "MU", "MA"], answer: "MO" },
  { question: "ヤ", options: ["YA", "YU", "YO", "E"], answer: "YA" },
  { question: "ユ", options: ["YU", "YO", "E", "YA"], answer: "YU" },
  { question: "ヨ", options: ["YO", "E", "YA", "YU"], answer: "YO" },
  { question: "ラ", options: ["RA", "RI", "RU", "RE"], answer: "RA" },
  { question: "リ", options: ["RI", "RU", "RE", "RA"], answer: "RI" },
  { question: "ル", options: ["RU", "RE", "RA", "RI"], answer: "RU" },
  { question: "レ", options: ["RE", "RA", "RI", "RU"], answer: "RE" },
  { question: "ロ", options: ["RO", "RE", "RU", "RA"], answer: "RO" },
  { question: "ワ", options: ["WA", "WO", "N", "RA"], answer: "WA" },
  { question: "ヲ", options: ["WO", "N", "RA", "WA"], answer: "WO" },
  { question: "ン", options: ["N", "M", "R", "SO"], answer: "N" },
  // Dakuten Characters
  { question: "ガ", options: ["GA", "GI", "GU", "GE"], answer: "GA" },
  { question: "ギ", options: ["GI", "GU", "GE", "GA"], answer: "GI" },
  { question: "グ", options: ["GU", "GE", "GA", "GI"], answer: "GU" },
  { question: "ゲ", options: ["GE", "GA", "GI", "GU"], answer: "GE" },
  { question: "ゴ", options: ["GO", "GE", "GU", "GA"], answer: "GO" },
  // Han-Dakuten Characters
  { question: "パ", options: ["PA", "PI", "PU", "PE"], answer: "PA" },
  { question: "ピ", options: ["PI", "PU", "PE", "PA"], answer: "PI" },
  { question: "プ", options: ["PU", "PE", "PA", "PI"], answer: "PU" },
  { question: "ペ", options: ["PE", "PA", "PI", "PU"], answer: "PE" },
  { question: "ポ", options: ["PO", "PE", "PA", "PI"], answer: "PO" },
  // Dakuten Combinations
  { question: "ギャ", options: ["GYA", "GYU", "GYO", "GE"], answer: "GYA" },
  { question: "ギュ", options: ["GYU", "GYO", "GE", "GYA"], answer: "GYU" },
  { question: "ギョ", options: ["GYO", "GE", "GYA", "GYU"], answer: "GYO" },
  { question: "ジャ", options: ["JA", "JU", "JO", "JE"], answer: "JA" },
  { question: "ジュ", options: ["JU", "JO", "JE", "JA"], answer: "JU" },
  { question: "ジョ", options: ["JO", "JE", "JA", "JU"], answer: "JO" },
  { question: "ビャ", options: ["BYA", "BYU", "BYO", "BE"], answer: "BYA" },
  { question: "ビュ", options: ["BYU", "BYO", "BE", "BYA"], answer: "BYU" },
  { question: "ビョ", options: ["BYO", "BE", "BYA", "BYU"], answer: "BYO" },
  { question: "ピャ", options: ["PYA", "PYU", "PYO", "PE"], answer: "PYA" },
  { question: "ピュ", options: ["PYU", "PYO", "PE", "PYA"], answer: "PYU" },
  { question: "ピョ", options: ["PYO", "PE", "PYA", "PYU"], answer: "PYO" },
  // Han-Dakuten Combinations
  { question: "キャ", options: ["KYA", "KYU", "KYO", "KE"], answer: "KYA" },
  { question: "キュ", options: ["KYU", "KYO", "KE", "KYA"], answer: "KYU" },
  { question: "キョ", options: ["KYO", "KE", "KYA", "KYU"], answer: "KYO" },
  { question: "シャ", options: ["SHA", "SHU", "SHO", "SE"], answer: "SHA" },
  { question: "シュ", options: ["SHU", "SHO", "SE", "SHA"], answer: "SHU" },
  { question: "ショ", options: ["SHO", "SE", "SHA", "SHU"], answer: "SHO" },
  { question: "チャ", options: ["CHA", "CHU", "CHO", "CHE"], answer: "CHA" },
  { question: "チュ", options: ["CHU", "CHO", "CHE", "CHA"], answer: "CHU" },
  { question: "チョ", options: ["CHO", "CHE", "CHA", "CHU"], answer: "CHO" },
  { question: "ニャ", options: ["NYA", "NYU", "NYO", "NE"], answer: "NYA" },
  { question: "ニュ", options: ["NYU", "NYO", "NE", "NYA"], answer: "NYU" },
  { question: "ニョ", options: ["NYO", "NE", "NYA", "NYU"], answer: "NYO" }
];

const kanjiCharacters = [
  { question: "一", options: ["One", "Two", "Three", "Four"], answer: "One" },
  { question: "二", options: ["Two", "Three", "Four", "Five"], answer: "Two" },
  { question: "三", options: ["Three", "Four", "Five", "Six"], answer: "Three" },
  { question: "四", options: ["Four", "Five", "Six", "Seven"], answer: "Four" },
  { question: "五", options: ["Five", "Six", "Seven", "Eight"], answer: "Five" },
  { question: "六", options: ["Six", "Seven", "Eight", "Nine"], answer: "Six" },
  { question: "七", options: ["Seven", "Eight", "Nine", "Ten"], answer: "Seven" },
  { question: "八", options: ["Eight", "Nine", "Ten", "Hundred"], answer: "Eight" },
  { question: "九", options: ["Nine", "Ten", "Hundred", "Thousand"], answer: "Nine" },
  { question: "十", options: ["Ten", "Hundred", "Thousand", "One"], answer: "Ten" },
  { question: "百", options: ["Hundred", "Thousand", "Ten", "One"], answer: "Hundred" },
  { question: "千", options: ["Thousand", "Ten", "One", "Hundred"], answer: "Thousand" },
  { question: "万", options: ["Ten Thousand", "One", "Hundred", "Thousand"], answer: "Ten Thousand" },
  { question: "円", options: ["Yen", "Dollar", "Euro", "Pound"], answer: "Yen" },
  { question: "時", options: ["Time", "Hour", "Day", "Week"], answer: "Time" },
  { question: "分", options: ["Minute", "Hour", "Day", "Month"], answer: "Minute" },
  { question: "本", options: ["Book", "Tree", "River", "Sun"], answer: "Book" },
  { question: "月", options: ["Month", "Sun", "Day", "Year"], answer: "Month" },
  { question: "年", options: ["Year", "Month", "Day", "Week"], answer: "Year" },
  { question: "日", options: ["Day", "Sun", "Month", "Week"], answer: "Day" },
  { question: "週", options: ["Week", "Day", "Month", "Year"], answer: "Week" },
  { question: "木", options: ["Tree", "Water", "Fire", "Earth"], answer: "Tree" },
  { question: "水", options: ["Water", "Tree", "Fire", "Earth"], answer: "Water" },
  { question: "火", options: ["Fire", "Water", "Wind", "Earth"], answer: "Fire" },
  { question: "土", options: ["Earth", "Tree", "Water", "Fire"], answer: "Earth" },
  { question: "金", options: ["Gold", "Water", "Fire", "Earth"], answer: "Gold" },
  { question: "白", options: ["White", "Black", "Red", "Blue"], answer: "White" },
  { question: "赤", options: ["Red", "Blue", "Green", "Yellow"], answer: "Red" },
  { question: "青", options: ["Blue", "Red", "Green", "Yellow"], answer: "Blue" },
  { question: "黒", options: ["Black", "White", "Red", "Blue"], answer: "Black" },
  { question: "田", options: ["Rice Field", "River", "Mountain", "Sun"], answer: "Rice Field" },
  { question: "山", options: ["Mountain", "River", "Rice Field", "Sun"], answer: "Mountain" },
  { question: "川", options: ["River", "Mountain", "Rice Field", "Sun"], answer: "River" },
  { question: "夜", options: ["Night", "Day", "Morning", "Evening"], answer: "Night" },
  { question: "朝", options: ["Morning", "Day", "Night", "Evening"], answer: "Morning" },
  { question: "昼", options: ["Daytime", "Morning", "Night", "Evening"], answer: "Daytime" },
  { question: "夕", options: ["Evening", "Day", "Morning", "Night"], answer: "Evening" },
  { question: "男", options: ["Man", "Woman", "Boy", "Girl"], answer: "Man" },
  { question: "女", options: ["Woman", "Man", "Girl", "Boy"], answer: "Woman" },
  { question: "子", options: ["Child", "Parent", "Adult", "Elder"], answer: "Child" },
  { question: "人", options: ["Person", "Tree", "Water", "Fire"], answer: "Person" },
  { question: "名", options: ["Name", "Person", "Tree", "Water"], answer: "Name" },
  { question: "友", options: ["Friend", "Enemy", "Stranger", "Acquaintance"], answer: "Friend" },
  { question: "学", options: ["Study", "Teach", "Learn", "Know"], answer: "Study" },
  { question: "校", options: ["School", "Work", "Home", "Store"], answer: "School" },
  { question: "先", options: ["Previous", "Next", "First", "Last"], answer: "Previous" },
  { question: "生", options: ["Life", "Death", "Birth", "Old Age"], answer: "Life" },
  { question: "行", options: ["Go", "Come", "Run", "Walk"], answer: "Go" },
  { question: "来", options: ["Come", "Go", "Run", "Walk"], answer: "Come" },
  { question: "食", options: ["Eat", "Drink", "Sleep", "Play"], answer: "Eat" },
  { question: "飲", options: ["Drink", "Eat", "Sleep", "Play"], answer: "Drink" },
  { question: "読", options: ["Read", "Write", "Speak", "Listen"], answer: "Read" },
  { question: "書", options: ["Write", "Read", "Speak", "Listen"], answer: "Write" },
  { question: "話", options: ["Speak", "Listen", "Read", "Write"], answer: "Speak" },
  { question: "聞", options: ["Listen", "Speak", "Read", "Write"], answer: "Listen" },
  { question: "見", options: ["See", "Look", "Watch", "Read"], answer: "See" },
  { question: "知", options: ["Know", "Learn", "Teach", "Study"], answer: "Know" },
  { question: "気", options: ["Spirit", "Energy", "Air", "Water"], answer: "Spirit" },
  { question: "天", options: ["Heaven", "Earth", "Sun", "Moon"], answer: "Heaven" },
  { question: "地", options: ["Earth", "Heaven", "Sun", "Moon"], answer: "Earth" },
  { question: "空", options: ["Sky", "Ground", "Sea", "Mountain"], answer: "Sky" },
  { question: "海", options: ["Sea", "Sky", "Ground", "Mountain"], answer: "Sea" },
  { question: "風", options: ["Wind", "Rain", "Sun", "Snow"], answer: "Wind" },
  { question: "雨", options: ["Rain", "Wind", "Sun", "Snow"], answer: "Rain" },
  { question: "雪", options: ["Snow", "Rain", "Wind", "Sun"], answer: "Snow" },
  { question: "花", options: ["Flower", "Tree", "Grass", "Leaf"], answer: "Flower" },
  { question: "木", options: ["Tree", "Water", "Fire", "Earth"], answer: "Tree" },
  { question: "草", options: ["Grass", "Tree", "Flower", "Leaf"], answer: "Grass" },
  { question: "花", options: ["Flower", "Tree", "Grass", "Leaf"], answer: "Flower" },
  { question: "道", options: ["Road", "Street", "Path", "Highway"], answer: "Road" },
  { question: "町", options: ["Town", "City", "Village", "Country"], answer: "Town" },
  { question: "市", options: ["City", "Town", "Village", "Country"], answer: "City" },
  { question: "村", options: ["Village", "Town", "City", "Country"], answer: "Village" },
  { question: "国", options: ["Country", "Town", "City", "Village"], answer: "Country" },
  { question: "会", options: ["Meet", "Join", "Leave", "Stay"], answer: "Meet" },
  { question: "社", options: ["Company", "Society", "Club", "Group"], answer: "Company" },
  { question: "田", options: ["Rice Field", "River", "Mountain", "Sun"], answer: "Rice Field" },
  { question: "家", options: ["House", "Home", "Building", "Room"], answer: "House" },
  { question: "店", options: ["Store", "Shop", "Market", "Restaurant"], answer: "Store" },
  { question: "本", options: ["Book", "Tree", "River", "Sun"], answer: "Book" },
  { question: "電", options: ["Electricity", "Water", "Fire", "Earth"], answer: "Electricity" },
  { question: "車", options: ["Car", "Bicycle", "Train", "Bus"], answer: "Car" },
  { question: "手", options: ["Hand", "Foot", "Head", "Leg"], answer: "Hand" },
  { question: "足", options: ["Foot", "Hand", "Head", "Leg"], answer: "Foot" },
  { question: "目", options: ["Eye", "Ear", "Nose", "Mouth"], answer: "Eye" },
  { question: "耳", options: ["Ear", "Eye", "Nose", "Mouth"], answer: "Ear" },
  { question: "鼻", options: ["Nose", "Eye", "Ear", "Mouth"], answer: "Nose" },
  { question: "口", options: ["Mouth", "Eye", "Ear", "Nose"], answer: "Mouth" },
  { question: "手", options: ["Hand", "Foot", "Head", "Leg"], answer: "Hand" },
  { question: "足", options: ["Foot", "Hand", "Head", "Leg"], answer: "Foot" },
  { question: "頭", options: ["Head", "Hand", "Foot", "Leg"], answer: "Head" },
  { question: "顔", options: ["Face", "Head", "Hand", "Foot"], answer: "Face" },
  { question: "体", options: ["Body", "Head", "Hand", "Foot"], answer: "Body" },
  { question: "心", options: ["Heart", "Mind", "Soul", "Spirit"], answer: "Heart" },
  { question: "意", options: ["意味", "思い", "気持ち", "感じ"], answer: "意味" }, // Meaning
  { question: "思", options: ["思う", "意見", "考える", "話す"], answer: "思う" }, // Think
  { question: "言", options: ["言う", "話す", "聞く", "書く"], answer: "言う" }, // Say
  { question: "話", options: ["話す", "言う", "聞く", "書く"], answer: "話す" }, // Talk
  { question: "聞", options: ["聞く", "話す", "言う", "書く"], answer: "聞く" }, // Listen
  { question: "書", options: ["書く", "読む", "話す", "聞く"], answer: "書く" }, // Write
  { question: "読", options: ["読む", "書く", "話す", "聞く"], answer: "読む" }, // Read
  { question: "出", options: ["出る", "入る", "行く", "来る"], answer: "出る" }, // Exit
  { question: "入", options: ["入る", "出る", "行く", "来る"], answer: "入る" }, // Enter
  { question: "行", options: ["行く", "来る", "出る", "入る"], answer: "行く" }, // Go
  { question: "来", options: ["来る", "行く", "出る", "入る"], answer: "来る" }, // Come
  { question: "会", options: ["会う", "知る", "合う", "見る"], answer: "会う" }, // Meet
  { question: "知", options: ["知る", "会う", "合う", "見る"], answer: "知る" }, // Know
  { question: "合", options: ["合う", "会う", "知る", "見る"], answer: "合う" }, // Match
  { question: "見", options: ["見る", "会う", "知る", "合う"], answer: "見る" }, // See
];

export { hiraganaCharacters, katakanaCharacters, kanjiCharacters };
